export default {
    unexpected_error: "Váratlan hiba történt [{1}]",
    command_does_not_exist: "Nincs ilyen parancs",

    welcome_message_not_found: "❌ Nincs beállítva üdvözlő üzenet",
    welcome_message_saved: "✅ Üdvözlő üzenet elmentve",
    welcome_message_removed: " Üdvözlő üzenet törölve",
    welcome_message_edit: "Üdvözlő üzenet szerkesztése",
    welcome_message_edit_label: "Üzenet",
    welcome_message_preview: "**ÜDVÖZLŐ ÜZENET ELŐNÉZETE:**\n\n{1}",
    welcome_message_save_btn: "Mentés",
    welcome_message_edit_btn: "Szerkesztés",
    welcome_message_remove_btn: "Törlés",
    welcome_message_updated: "🔄 Üzenet frissítve",
    
    enter_sorsolas: "😎 Beléptél a sorsolásba",
    sorsolas_not_found: "❌ Nincs ilyen sorsolás",
    sorsolas_started: "✅ A sorsolás elindult",
    sorsolas_discarded: "❌ Sorsolás elvetve",
    sorsolas_winner: "A sorsolást {1} nyerte 🎉",
    sorsolas_closed: "✅ A sorsolás lezárva\n**Nyertes:** {1}",
    sorsolas_new_modal_title: "Sorsolás indítása",
    sorsolas_new_modal_time: "Időtartam (perc)",
    sorsolas_new_modal_emoji: "Gomb emoji",
    sorsolas_new_modal_btn_text: "Gomb felirat",
    sorsolas_new_modal_text: "Üzenet",
    sorsolas_new_loading: "Betöltés...",
    sorsolas_new_preview: "SORSOLÁS ÜZENET ELŐNÉZET:**\n\n{1}",
    sorsolas_new_send_btn: "Indítás",
    sorsolas_new_discard_btn: "Elvetés",

    roleselect_new_modal_title: "Új rang választó",
    roleselect_new_modal_text: "Üzenet",
    roleselect_new_preview: "RANG VÁLASZTÓ ÜZENET ELŐNÉZET:**\n\n{1}",
    roleselect_new_select_placeholder: "Válassz egy rangot...",
    roleselect_new_send_btn: "Küldés",
    roleselect_new_discard_btn: "Elvetés",
    roleselect_new_saved: "✅ Rang választó elmentve",
    roleselect_new_discarded: "❌ Rang választó elvetve",
    roleselect_new_role_title: "Új rang hozzáadása",
    roleselect_new_role_btn_label: "Gomb szöveg",
    roleselect_new_role_btn_emoji: "Gomb emoji",
    roleselect_selected: "Már {1} vagy",
}
